[tests] clang requires more explicit types for decltype comparison here.
murraycu/murrayc-tuple-utils pull request #4
Opened 2018-12-21 12:30 UTC by Fohlen

This also fixes the old-style casts (which are warnings in `clangs` default compilation mode).
I have manually run the `test_tuple_transform_each` on my OSX and can verify that all 9 tests run successfully.

2019-01-10 08:26 UTC, murraycu requested changes

2019-01-10 08:26 UTC, murraycu commented on tests/test_tuple_for_each.cc
> -    auto t_original = std::make_tuple(1, (double)2.1f, 3);
Thanks, but please put these cast improvements in a separate commit.

2019-01-10 08:26 UTC, murraycu commented on tests/test_tuple_transform_each.cc
> -    auto t_transformed =
I'm surprised that this is necessary, though I believe you. Please mention the exact compiler error in the commit message so that "git blame" provides some explanation for this line of code.

2020-01-01 21:46 UTC, murraycu commented
I would still like to take these impovements, please.

2020-01-05 15:58 UTC, Fohlen commented
Unfortunately I cannot build the latest master any longer on OSX because I keep running into:

```
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [libmurrayc-tuple-utils-1.0.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

PS: A good tip for future contributions, if you have a small repository with little community, it is not the wisest to stall pull requests for a long time. As seen with this PR, some things will change and break. Especially if your requested changes are changes to the commit history, which can be easily fixed by the maintainer rather than the author, this situation could/can be avoided 👍

2020-01-05 22:52 UTC, murraycu commented
I have pushed your uses of static_cast<> to master.

2020-01-05 22:58 UTC, closed without merging